### ISSUE TITLE
Return type

### ISSUE THREAD

**Issue by dfalbel** [t-kalinowski/tfautograph#6]
Consider the following:

``` r
library(tensorflow)
library(tfautograph)
square_if_positive <- function(x) {
  if (x > 0){
    x <- x * x
  } else {
   x <- 0 
  }
  x
}
square_if_positive_graph <- autograph(square_if_positive)
square_if_positive_graph(tf$constant(10))
#> tf.Tensor(100.0, shape=(), dtype=float32)
square_if_positive_graph(tf$constant(-10))
#> [1] 0
```

Do you think we should make sure that the second returns a Tensor like in Python? (You can see it [here](https://colab.research.google.com/drive/1x1D4Fom6qdIdkjyS8g32_gZbEwCvf5vm)

**Comment by t-kalinowski** [comment]
Thanks, this is something I only started to understand better recently (I spent a few hours getting familiar with 2.0 finally this week). 
What you call `square_if_positive_graph` is not actually a graphed function, it still execute eagerly (hence why `x` is never coerced in the `else` branch). In eager mode, we don't even call `tf.cond`, and dispatch directly to R's `if`, effectively evaluating the expression ```if(cond$`___bool__`())``` 

See this other example that behaves as you'd expect (note, you'll need to pull from the latest master, there was a minor bug I just fixed to make this work in 2.0.0rc0):
``` r
library(tensorflow)
library(tfautograph)
square_if_positive <- function(x) {
  if (x > 0){
    x <- x * x
  } else {
    x <- 0 
  }
  x
}
square_if_positive_eager <- autograph(square_if_positive)
square_if_positive_graph <- tf_function(square_if_positive_eager)
square_if_positive_graph(tf$constant(10))
#> tf.Tensor(100.0, shape=(), dtype=float32)
square_if_positive_graph(tf$constant(-10))
#> tf.Tensor(0.0, shape=(), dtype=float32)
```

<sup>Created on 2019-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by t-kalinowski** [comment]
also, I think the idiomatic way I'd suggest people us autograph is not necessarily 
```r
fn <- funciton(...) {...}
ag_fn <- autograph(fn)
```
but rather
```r
fn <- autograph(function(...) {...})
```
Though of course I intend to support both uses.

**Comment by dfalbel** [comment]
I see it now. The python equivalent for what `autograph` is doing is like:

```
def square_if_positive2(x):
  if x > 0:
    x = x * x
  else:
    x = 0.0
  return x

x = tf.autograph.to_graph(square_if_positive2)

print(x(tf.constant(9.0)))
print(x(tf.constant(-9.0)))
```

Which will output the same as the first example. Very insteresting!

So `tf.function` does some more work as stated in the docs:

> Unlike tf.function, to_graph is a low-level transpiler that converts Python code to TensorFlow graph code. It does not implement any caching, variable management or create any actual ops, and is best used where greater control over the generated TensorFlow graph is desired. Another difference from tf.function is that to_graph will not wrap the graph into a TensorFlow function or a Python callable. Internally, tf.function uses to_graph.

**Comment by t-kalinowski** [comment]
One followup note: These semantics of avoiding automatic conversion when executing eagerly are also how `tf.cond` itself behaves when called directly. 
``` r
library(tensorflow)
tf$version$VERSION
#> [1] "2.0.0-rc0"

bool <- tf$convert_to_tensor(TRUE)

tf$cond(
  bool,
  function() {cat("Tracing true branch\n"); 1},
  function() {cat("Tracing false branch\n"); 0}
)
#> Tracing true branch
#> [1] 1
```

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note, the false branch is never traced, and the return value from the true branch is not coerced to a tensor. This is why I feel comfortable completely bypassing calling `tf.cond()` when autographing `if` when `cond` is an eager tensor.
